name: Run Test


#Trigger the workflow on every push or pull request to the main branch
on:
  push:
    branches:
      -main
    pull_request:
      branches:
        -main
jobs:
  test:
    run-on: ubuntu-latest

    steps:
      #Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    #Set up Node.js enviroment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    #Install dependencies
      -name: Install dependencies
      run: npm install

    # Run test
    -name: Run tests
    run: npx jest